[test]
commands = [
    "cargo test",
]

[build-release]
commands = [
    "cargo build --release",
    "cp target/release/cinderella /opt/cinderella/.cinderella-{{ branch }}",
    "rm /opt/cinderella/cinderella-{{ branch }}",
    "mv /opt/cinderella/.cinderella-{{ branch }} /opt/cinderella/cinderella-{{ branch }}",
]
