[test]
commands = [
    "cargo test",
]

[build-master]
# Always build the latest master for usage on my server
commands = [
    "cargo build --release",
    "cp target/release/cinderella /opt/cinderella/.cinderella",
    # use -f on deletion to avoid errors if file does not exist
    "rm -f /opt/cinderella/cinderella",
    "mv /opt/cinderella/.cinderella /opt/cinderella/cinderella",
]
when = "\"%BRANCH\" == \"master\""

[build-release]
commands = [
    "cargo build --release",
    "cp target/release/cinderella \"/opt/cinderella/cinderella-%TAG\"",
]
when = "\"%REFTYPE\" == \"tag\""
