[test]
commands = [
    "cargo test",
]

[build-master]
# Always build the latest master for usage on my server
commands = [
    "make",
    "make install",
]
when = "\"%BRANCH\" == \"master\""

[build-release]
commands = [
    # set the tag number as tool version
    "sed -i -e 's/^version = .*/version = \"%TAG\"/' Cargo.toml",

    "make",
    "cp target/release/cinderella \"/opt/cinderella/cinderella-%TAG\"",
]
when = "\"%REFTYPE\" == \"tag\""
