[test]
commands = [
    "cargo test",
]

[build-release]
commands = [
    "cargo build --release",
    "cp target/release/cinderella /opt/cinderella/.cinderella",
    # use -f on deletion to avoid errors if file does not exist
    "rm -f /opt/cinderella/cinderella",
    "mv /opt/cinderella/.cinderella /opt/cinderella/cinderella",
]
when = "\"%BRANCH\" == \"master\""
