#!/bin/bash
# Execute Cinderella continuous integration with the user performing the push.
# Sources the user's .bash_profile. This is e.g. required for rust toolchains
# that were installed with rustup.

echo "Executing Cinderella"
user=$(whoami)
echo "Current user: $user"

source /home/$user/.bash_profile

reftype=$(sed -n 's/[^\/]\+\/\([^\/]\+\)\/[^\/]\+/\1/p' <<< $1)
name=$(basename "$1")

if [ "$reftype" = "heads" ]; then
    echo "Will build branch $name"
    nohup /opt/cinderella/cinderella run "$PWD" --branch "$name" &>/dev/null &
elif [ "$reftype" = "tags" ]; then
    echo "Will build tag $name"
    nohup /opt/cinderella/cinderella run "$PWD" --tag "$name" &>/dev/null &
else
    echo "Unknown ref type: $1"
fi
